// Shadow Slave v3.4 — Operational SAVE Validator
(function(){
'use strict';
const HOST=(window.parent||window);const INSTANCE='__SHADOW_SLAVE_SAVE_VALIDATOR_V34__';if(HOST[INSTANCE])return;HOST[INSTANCE]=true;
const R=HOST.ShadowSlaveV34Rules||{};
const RANKS=['mundane','dormant','awakened','ascended','transcendent','supreme','sacred','divine'];
const CLASSES=['beast','monster','demon','devil','tyrant','terror','titan'];
const KNOW_PATHS=new Set(['witnessed','told','public','ability','vision','memory_or_vision','inference','user_correction']);
const HIGH_REWARD=/rank|class|core|aspect|ability|true\s*name|domain|lineage/i;
let lastGood=null,guard=false,timer=null,lastReport={status:'INIT',issues:[],at:0};
function clone(x){return JSON.parse(JSON.stringify(x||{}));}function norm(x){return String(x??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[\s-]+/g,'_');}
function findSheet(data,key,name){if(data?.[key])return data[key];for(const k of Object.keys(data||{})){if(data[k]?.name===name)return data[k];}return null;}
function ctx(sheet){if(!sheet||!Array.isArray(sheet.content)||!Array.isArray(sheet.content[0]))return null;const h=sheet.content[0].map(String),m={};h.forEach((x,i)=>m[x]=i);return {sheet,h,m,rows:sheet.content.slice(1).filter(Array.isArray)};}
function get(r,c,n,d=''){const i=c?.m?.[n];return i===undefined?d:(r[i]??d);}function set(r,c,n,v){let i=c.m[n];if(i===undefined){c.m[n]=c.h.length;c.h.push(n);c.sheet.content[0].push(n);i=c.m[n];for(const row of c.rows)while(row.length<c.h.length)row.push('');}while(r.length<c.h.length)r.push('');if(String(r[i]??'')!==String(v??'')){r[i]=v;return true;}return false;}
function rowsBy(c,col){const out=new Map();if(!c)return out;for(const r of c.rows){const k=String(get(r,c,col,'')).trim();if(k)out.set(k,r);}return out;}function issue(list,rule,severity,target,detail){list.push({rule,severity,target,detail});}
function hasEvent(code,chron){const x=String(code||'').trim();if(!x)return false;if(/^(GENESIS|SYSTEM_INIT|USER_CORRECTION|FIRST_NIGHTMARE)(:|$)/i.test(x))return true;return chron.has(x);}
function rankIndex(v){return RANKS.indexOf(norm(v));}function classIndex(v){return CLASSES.indexOf(norm(v));}function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
async function canonRecord(id){const rid=String(id||'').trim();if(!/^SSREC_\d{6}$/i.test(rid))return null;try{return await HOST.ShadowSlaveCanonDB?.getRecord?.(rid)||null;}catch(e){return null;}}
function ruleFromRow(r,c){return R.normalizeFlawRule?R.normalizeFlawRule({ID:get(r,c,'Rule ID'),Name:get(r,c,'Name'),Description:get(r,c,'Description'),Type:get(r,c,'Type'),State:get(r,c,'State'),trigger_events:get(r,c,'Trigger Events'),condition:get(r,c,'Condition'),required_actions:get(r,c,'Required Actions'),forbidden_actions:get(r,c,'Forbidden Actions'),consequence_type:get(r,c,'Consequence Type'),consequence_effect:get(r,c,'Consequence Effect'),planning_avoid:get(r,c,'Planning Avoid Goals'),planning_required:get(r,c,'Planning Required Considerations'),observable_effect:get(r,c,'Narrative Observable Effect'),internal_effect:get(r,c,'Narrative Internal Effect'),exceptions:get(r,c,'Exceptions'),pre_generation:get(r,c,'Pre Generation'),post_generation:get(r,c,'Post Generation'),allowed_acquisition_methods:get(r,c,'Allowed Acquisition Methods'),cost_resource:get(r,c,'Cost Resource'),cost_amount:get(r,c,'Cost Amount'),provenance:get(r,c,'Provenance')}):null;}
function activeRule(player,flaws){if(!flaws)return null;const id=player?.rows?.[0]?String(get(player.rows[0],player,'Flaw Rule ID','')).trim():'';let row=id?flaws.rows.find(r=>String(get(r,flaws,'Rule ID','')).trim()===id):null;if(!row)row=flaws.rows.find(r=>/^active$/i.test(String(get(r,flaws,'State',''))));return row?ruleFromRow(row,flaws):null;}
function appendViolation(vio,rule,eventType,summary,detail){if(!vio)return;let max=0;for(const r of vio.rows){const m=String(get(r,vio,'Violation ID','')).match(/RULEV_(\d+)/i);if(m)max=Math.max(max,Number(m[1]));}const id='RULEV_'+String(max+1).padStart(4,'0');const row=Array(vio.h.length).fill('');set(row,vio,'row_id',String(vio.rows.length+1));set(row,vio,'Violation ID',id);set(row,vio,'Rule ID',rule||'SYSTEM');set(row,vio,'Event Type',eventType||'UNKNOWN');set(row,vio,'Action Summary',String(summary||'').slice(0,300));set(row,vio,'Result','BLOCKED_OR_REPAIRED');set(row,vio,'Detail',String(detail||'').slice(0,500));vio.sheet.content.push(row);vio.rows.push(row);while(vio.rows.length>30){vio.sheet.content.splice(1,1);vio.rows.shift();}return id;}
async function validateTables(current,previous){
 const data=clone(current),prev=previous?clone(previous):null,issues=[];let changed=false;
 const runtime=ctx(findSheet(data,'sheet_ss_runtime','SS Runtime State')),player=ctx(findSheet(data,'sheet_ss_player','SS Player State')),inv=ctx(findSheet(data,'sheet_ss_inventory','SS Inventory')),rel=ctx(findSheet(data,'sheet_ss_relationships','SS Relationships')),know=ctx(findSheet(data,'sheet_ss_knowledge','SS Knowledge')),div=ctx(findSheet(data,'sheet_ss_divergence','SS Divergence')),rew=ctx(findSheet(data,'sheet_ss_reward','SS Reward Log')),chr=ctx(findSheet(data,'sheet_ss_chronicle','Bảng Kỷ Yếu')),flaws=ctx(findSheet(data,'sheet_ss_flaw_rules','SS Flaw Rules')),night=ctx(findSheet(data,'sheet_ss_nightmare','SS Nightmare State')),vio=ctx(findSheet(data,'sheet_ss_violations','SS Rule Violations'));
 const prevPlayer=prev?ctx(findSheet(prev,'sheet_ss_player','SS Player State')):null,prevChr=prev?ctx(findSheet(prev,'sheet_ss_chronicle','Bảng Kỷ Yếu')):null,prevNight=prev?ctx(findSheet(prev,'sheet_ss_nightmare','SS Nightmare State')):null;
 // SAVE history append-only.
 if(chr&&prevChr){const cur=rowsBy(chr,'Chỉ Mục Mã Hóa'),old=rowsBy(prevChr,'Chỉ Mục Mã Hóa');for(const [code,oldRow] of old){const now=cur.get(code);if(!now){chr.sheet.content.push(clone(oldRow));chr.rows.push(chr.sheet.content.at(-1));changed=true;issue(issues,'SAVE_HISTORY_APPEND_ONLY','error',code,'Deleted prior memory restored.');}else if(JSON.stringify(now)!==JSON.stringify(oldRow)){const i=chr.sheet.content.indexOf(now);chr.sheet.content[i]=clone(oldRow);changed=true;issue(issues,'SAVE_HISTORY_IMMUTABLE_PRIOR','error',code,'Modified prior memory reverted.');}}}
 if(chr){const used=new Set();let max=0;for(const r of chr.rows){const c=String(get(r,chr,'Chỉ Mục Mã Hóa','')).trim(),m=c.match(/^AM(\d+)$/i);if(m){max=Math.max(max,+m[1]);if(!used.has(c.toUpperCase())){used.add(c.toUpperCase());continue;}}max++;const nc='AM'+String(max).padStart(4,'0');changed|=set(r,chr,'Chỉ Mục Mã Hóa',nc);used.add(nc);issue(issues,'SAVE_MEMORY_CODE_REPAIR','warn',nc,'Missing/duplicate AM code normalized.');}}
 const chron=rowsBy(chr,'Chỉ Mục Mã Hóa');
 // Reward provenance.
 const validRewards=[];if(rew){for(const r of rew.rows){const uid=String(get(r,rew,'Reward UID','')).trim()||`row:${get(r,rew,'row_id','?')}`,kind=String(get(r,rew,'Kind','')),src=String(get(r,rew,'Source Event','')).trim(),auth=String(get(r,rew,'Rule Authority','')).trim(),cost=String(get(r,rew,'Cost','')).trim();let ok=true,why=[];if(!src||!hasEvent(src,chron)){ok=false;why.push('Source Event unresolved.');}if(!auth){ok=false;why.push('Rule Authority missing.');}if(/^SSREC_\d{6}$/i.test(auth)){if(!await canonRecord(auth)){ok=false;why.push('Canon Rule Authority ID not found.');}}else if(auth&&!/^(SAVE_RULE|GENESIS_RULE|USER_CORRECTION|SYSTEM_RULE|FIRST_NIGHTMARE):/i.test(auth)){ok=false;why.push('Invalid Rule Authority namespace.');}if(HIGH_REWARD.test(kind)&&!cost){ok=false;why.push('High-impact reward/progression requires cost/condition.');}const ns=night?.rows?.[0]?String(get(night.rows[0],night,'State','')).toUpperCase():'';if(ns==='ACTIVE'&&/memory|echo|shadow|aspect|ability|rank|class|core|true\s*name/i.test(kind)){ok=false;why.push('First Nightmare ACTIVE: high-impact reward is premature before Appraisal.');}
 changed|=set(r,rew,'Validated',ok?'Yes':'No');changed|=set(r,rew,'Rejection Reason',ok?'':why.join(' '));if(ok)validRewards.push({uid,kind:norm(kind),name:norm(get(r,rew,'Name','')),src,auth});else issue(issues,'REWARD_PROVENANCE','error',uid,why.join(' '));}}
 // Progression gate.
 if(player&&player.rows[0]&&prevPlayer&&prevPlayer.rows[0]){const r=player.rows[0],o=prevPlayer.rows[0],ev=String(get(r,player,'Last Progression Event','')).trim(),auth=String(get(r,player,'Last Progression Authority','')).trim();const authorityOk=!!ev&&hasEvent(ev,chron)&&!!auth&&(/^SSREC_\d{6}$/i.test(auth)||/^(SAVE_RULE|GENESIS_RULE|USER_CORRECTION|SYSTEM_RULE|FIRST_NIGHTMARE):/i.test(auth));for(const [field,indexer] of [['Rank',rankIndex],['Class',classIndex]]){const a=indexer(get(o,prevPlayer,field,'')),b=indexer(get(r,player,field,''));if(a>=0&&b>=0&&a!==b&&(b<a||b-a>1||(!authorityOk&&b>a))){changed|=set(r,player,field,get(o,prevPlayer,field,''));issue(issues,'PROGRESSION_GATE','error',field,'Illegal progression transition reverted.');}}const oc=num(get(o,prevPlayer,'Soul Cores','')),nc=num(get(r,player,'Soul Cores',''));if(oc!==null&&nc!==null&&oc!==nc&&(nc<0||nc>7||nc<oc||nc-oc>1||(!authorityOk&&nc>oc))){changed|=set(r,player,'Soul Cores',get(o,prevPlayer,'Soul Cores',''));issue(issues,'CORE_GATE','error','Soul Cores','Illegal core change reverted.');}}
 // First Nightmare state machine + blueprint/live invariants in SAVE mirror.
 const nr=night?.rows?.[0],pn=prevNight?.rows?.[0];if(nr){let ns=String(get(nr,night,'State','INACTIVE')).toUpperCase(),os=pn?String(get(pn,prevNight,'State','INACTIVE')).toUpperCase():ns;const success=/^(true|yes|1)$/i.test(String(get(nr,night,'Success Confirmed','')))||/^success$/i.test(String(get(nr,night,'Outcome',''))),app=/^(committed|complete|completed)$/i.test(String(get(nr,night,'Appraisal State','')));const tr=R.allowedNightmareTransition?R.allowedNightmareTransition(os,ns,{successConfirmed:success,appraisalCommitted:app}):{ok:true};if(!tr.ok&&pn){changed|=set(nr,night,'State',os);ns=os;issue(issues,'FIRST_NIGHTMARE_TRANSITION','error','State',tr.reason);appendViolation(vio,'FIRST_NIGHTMARE_STATE','STATE_TRANSITION',`${os}->${String(get(nr,night,'State',''))}`,tr.reason);}
   if(['COUNTDOWN','ENTERING','ACTIVE'].includes(ns)&&player?.rows?.[0]){const pr=player.rows[0];for(const [field,locked] of [['Aspect State','UNAWAKENED'],['Flaw State','UNREVEALED'],['True Name State','UNREVEALED']])if(String(get(pr,player,field,'')).toUpperCase()!==locked){changed|=set(pr,player,field,locked);issue(issues,'BLUEPRINT_LIVE_FIREWALL','error',field,`Forced ${field}=${locked} during First Nightmare ${ns}.`);}if(rankIndex(get(pr,player,'Rank',''))>rankIndex('mundane')){changed|=set(pr,player,'Rank','Mundane');issue(issues,'FIRST_NIGHTMARE_RANK_LOCK','error','Rank','Player real rank cannot advance before Appraisal.');}}
 }
 // Active structured Flaw.
 const fr=activeRule(player,flaws);if(player?.rows?.[0]&&fr){changed|=set(player.rows[0],player,'Flaw Rule ID',fr.ID);changed|=set(player.rows[0],player,'Flaw Rule Type',fr.Type);}
 if(inv){for(const r of inv.rows){const uid=String(get(r,inv,'Item UID','')).trim()||String(get(r,inv,'Name','')).trim(),method=norm(get(r,inv,'Acquisition Method','')),ev=String(get(r,inv,'Acquisition Event','')).trim();let blocked=false,why=[];if(!ev||!hasEvent(ev,chron)){blocked=true;why.push('Acquisition Event missing/unresolved.');}if(fr?.Type==='ITEM_RESTRICTION'){const allowed=new Set((fr.Parameters?.Allowed_Acquisition_Methods||[]).map(norm));const allow=allowed.size?allowed:(R.ALLOW_UNEARNED||new Set());const deny=R.BLOCK_UNEARNED||new Set();if(deny.has(method)||(method&&!allow.has(method))){blocked=true;why.push(`Active Flaw ${fr.ID} makes this item unusable for self through acquisition method ${method||'UNKNOWN'}.`);}}if(/reward/.test(method)&&!validRewards.some(x=>x.src===ev||x.name===norm(get(r,inv,'Name','')))){blocked=true;why.push('Reward item lacks validated Reward Log provenance.');}if(blocked){changed|=set(r,inv,'Usable','No');changed|=set(r,inv,'State','BLOCKED_BY_VALIDATOR');issue(issues,'INVENTORY_GATE','error',uid,why.join(' '));appendViolation(vio,fr?.ID||'INVENTORY_GATE','ITEM_USE',uid,why.join(' '));}}}
 // Relationship clamp.
 if(rel){for(const r of rel.rows)for(const f of ['Trust','Respect','Affection','Attraction','Fear','Suspicion','Hostility','Loyalty','Vulnerability']){const v=num(get(r,rel,f,''));if(v!==null){const c=Math.max(-100,Math.min(100,v));if(c!==v){changed|=set(r,rel,f,String(c));issue(issues,'RELATIONSHIP_CLAMP','warn',String(get(r,rel,'Entity ID','')),`${f} clamped.`);}}}}
 // Knowledge gate.
 const rr=runtime?.rows?.[0],cur=num(rr?get(rr,runtime,'Chapter',''):null);if(know){for(const r of know.rows){const uid=String(get(r,know,'Knowledge UID','')).trim()||`row:${get(r,know,'row_id','?')}`,by=norm(get(r,know,'Acquired By','')),ev=String(get(r,know,'Acquired Event','')).trim(),rid=String(get(r,know,'Canon Record ID','')).trim();let ok=KNOW_PATHS.has(by),why=[];if(!ok)why.push('Unknown/absent information path.');let rec=null;if(rid){rec=await canonRecord(rid);if(!rec){ok=false;why.push('Canon Record ID not found.');}}if(rec&&cur!==null&&Number(rec.chapter_start||0)>cur&&(!['witnessed','told','ability','vision','memory_or_vision','user_correction'].includes(by)||!ev||!hasEvent(ev,chron))){ok=false;why.push('Future-canon fact requires explicit in-world reveal event.');}changed|=set(r,know,'Validation State',ok?'VALID':'REJECTED');changed|=set(r,know,'Rejection Reason',ok?'':why.join(' '));if(!ok)issue(issues,'KNOWLEDGE_GATE','error',uid,why.join(' '));}}
 if(div){for(const r of div.rows){const sev=norm(get(r,div,'Severity',''));if(sev&&!['minor','moderate','major','worldline'].includes(sev)){changed|=set(r,div,'Severity','moderate');issue(issues,'DIVERGENCE_SEVERITY','warn',String(get(r,div,'Divergence UID','')),'Unknown severity normalized.');}}}
 return {data,changed:Boolean(changed),issues};
}
async function run(){if(guard)return;const api=HOST.ShadowSlaveAutoDBAPI;if(!api?.exportTableAsJson)return;const current=clone(api.exportTableAsJson()||{});if(!current.sheet_ss_runtime)return;if(!lastGood){lastGood=clone(current);lastReport={status:'BASELINED',issues:[],at:Date.now()};return;}try{const res=await validateTables(current,lastGood);lastReport={status:res.issues.some(x=>x.severity==='error')?'REPAIRED_OR_REJECTED':'PASS',issues:res.issues,at:Date.now()};if(res.changed){guard=true;try{await api.importTableAsJson(JSON.stringify(res.data),{persist:true});lastGood=clone(res.data);console.warn('[Shadow Slave SAVE Validator v3.4] repaired/rejected',res.issues);}finally{guard=false;}}else lastGood=clone(current);}catch(e){lastReport={status:'ERROR',issues:[{detail:String(e)}],at:Date.now()};console.warn('[Shadow Slave SAVE Validator v3.4] error',e);}}
function schedule(){if(guard)return;clearTimeout(timer);timer=setTimeout(run,120);}async function bind(timeout=25000){const s=Date.now();while(Date.now()-s<timeout){const api=HOST.ShadowSlaveAutoDBAPI;if(api?.registerTableUpdateCallback){lastGood=clone(api.exportTableAsJson?.()||{});api.registerTableUpdateCallback(schedule);console.log('[Shadow Slave SAVE Validator v3.4] operational validator bound.');return true;}await new Promise(r=>setTimeout(r,250));}console.warn('[Shadow Slave SAVE Validator v3.4] AutoDB API unavailable.');return false;}
HOST.ShadowSlaveSaveValidator={validateTables,run,status:()=>clone(lastReport),resetBaseline:()=>{lastGood=clone(HOST.ShadowSlaveAutoDBAPI?.exportTableAsJson?.()||{});return true;}};bind();
})();
